--- #PVC POSTGRES AND PVC JIRA
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
    app: jira-db
  name: jira-db-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: vmware-silver

--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
    app: jira
  name: jira-home-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: vmware-silver
